name: 'GitVersion'
description: '(Installs GitVersion and) Runs GitVersion and exposes the versioning action outputs'
branding:
  icon: 'pocket'
  color: 'green'
outputs:
  Major:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  Minor:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  Patch:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  PreReleaseTag:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  PreReleaseTagWithDash:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  PreReleaseLabel:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  PreReleaseNumber:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  WeightedPreReleaseNumber:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  BuildMetaData:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  BuildMetaDataPadded:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  FullBuildMetaData:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  MajorMinorPatch:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  SemVer:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  LegacySemVer:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  LegacySemVerPadded:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  AssemblySemVer:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  AssemblySemFileVer:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  FullSemVer:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  InformationalVersion:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  BranchName:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  Sha:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  ShortSha:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  NuGetVersionV2:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  NuGetVersion:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
  NuGetPreReleaseTagV2:
    description: 'See GitVersion docs about output: https://gitversion.net/docs/more-info/variables'
runs:
  using: 'node12'
  main: 'index.js'

# runs:
#   using: composite
#   steps:
#     - id: gitversion
#       run: ${{ github.action_path }}/action.ps1 -repository ${{ github.repository }} -ref ${{ github.ref }} -sha ${{ github.sha }}
#       shell: pwsh
